# Generated by Django 2.2.6 on 2020-01-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Address', models.CharField(max_length=50, verbose_name='Office Address')),
                ('Contact', models.CharField(max_length=20, verbose_name='Contact Number')),
                ('Expertise', models.CharField(max_length=30)),
                ('Chamber', models.CharField(max_length=20, verbose_name='Chamber Number')),
                ('minFee', models.IntegerField(verbose_name='Minimm Fee')),
                ('maxFee', models.IntegerField(verbose_name='Maximum Fee ')),
                ('officeHours', models.CharField(max_length=60, verbose_name='Office Hours')),
            ],
        ),
    ]
