# Generated by Django 2.2.6 on 2020-01-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_lawyer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
